<?xml version="1.0" encoding="UTF-8"?>
<testng-results>
    <suite name="">
                <test name="Home page on mobile">
            <class name="http://example.com/page1 400x600">
                <test-method status="FAIL" signature="check homepage.spec --include all,mobile" name="check homepage.spec --include all,mobile" duration-ms="0" started-at="{expected-date}" finished-at="{expected-date}" description="">
                </test-method>
            </class>
            <class name="http://example.com/page2 600x700">
                <test-method status="FAIL" signature="check homepage.spec --include all,mobile" name="check homepage.spec --include all,mobile" duration-ms="0" started-at="{expected-date}" finished-at="{expected-date}" description="">
                </test-method>
                <test-method status="FAIL" signature="global error" name="global error" duration-ms="0" started-at="{expected-date}" finished-at="{expected-date}" description="">
                    <exception class="net.mindengine.galen.components.report.FakeException">
                        <message>net.mindengine.galen.components.report.FakeException: Some exception here</message>
                        <full-stacktrace>net.mindengine.galen.components.report.FakeException: Some exception here
\t    at net.mindengine.someclass.SomeClass.method1(SomeClass.java:4)
\t    at net.mindengine.someclass.SomeClass2.method2(SomeClass2.java:5)
\t    at net.mindengine.someclass.SomeClass3.method3(SomeClass3.java:6)
</full-stacktrace>
                    </exception>
                </test-method>
            </class>
        </test>
    </suite>
</testng-results>