<?xml version="1.0" encoding="UTF-8"?>
<testng-results>
    <suite name="page1.test">
        <test name="http://example.com/page1 400x600">
            <class name="objectA1">
                <test-method status="FAIL" signature="objectA1: inside: other-object 10px left" name="inside: other-object 10px left" duration-ms="0" started-at="{expected-date}" finished-at="{expected-date}" description="">
                    <exception class="Error_SpecInside">
                        <short-stacktrace>objectA1 is not inside other-object</short-stacktrace>
                    </exception>
                </test-method>
                <test-method status="PASS" signature="objectA1: width: 10 to 20px" name="width: 10 to 20px" duration-ms="0" started-at="{expected-date}" finished-at="{expected-date}" description="">
                </test-method>
            </class>
            <class name="objectA2">
                <test-method status="PASS" signature="objectA2: width: 10 to 20px" name="width: 10 to 20px" duration-ms="0" started-at="{expected-date}" finished-at="{expected-date}" description="">
                </test-method>
                <test-method status="FAIL" signature="objectA2: width: 10px" name="width: 10px" duration-ms="0" started-at="{expected-date}" finished-at="{expected-date}" description="">
                    <exception class="Error_SpecWidth">
                        <short-stacktrace>objectA2 width is 20px instead of 10px</short-stacktrace>
                    </exception>
                </test-method>
            </class>
        </test>
        <test name="http://example.com/page2 600x700">
            <class name="objectB1">
                <test-method status="PASS" signature="objectB1: width: 10 to 20px" name="width: 10 to 20px" duration-ms="0" started-at="{expected-date}" finished-at="{expected-date}" description="">
                </test-method>
                <test-method status="FAIL" signature="objectB1: inside: other-object 10px left" name="inside: other-object 10px left" duration-ms="0" started-at="{expected-date}" finished-at="{expected-date}" description="">
                    <exception class="Error_SpecInside">
                        <short-stacktrace>objectB1 is not inside other-object
second error message with &lt;xml&gt; &amp;tags</short-stacktrace>
                    </exception>
                </test-method>
            </class>
            <class name="objectB2">
                <test-method status="PASS" signature="objectB2: height: 100px" name="height: 100px" duration-ms="0" started-at="{expected-date}" finished-at="{expected-date}" description="">
                </test-method>
            </class>
            <class name="global error">
                <test-method status="FAIL" signature="global error" name="global error" duration-ms="0" started-at="{expected-date}" finished-at="{expected-date}" description="">
                    <exception class="java.lang.NullPointerException">
                        <short-stacktrace>java.lang.NullPointerException: Some exception here
\t    at net.mindengine.galen.components.report.ReportingListenerTestUtils.performSampleReporting(ReportingListenerTestUtils.java:100)
\t    at net.mindengine.galen.tests.runner.ReportingListenerTest.shouldReport_inTestNgFormat_successfully(ReportingListenerTest.java:49)
\t    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
\t    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
\t    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
\t    at java.lang.reflect.Method.invoke(Method.java:597)
\t    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
\t    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
\t    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
\t    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
\t    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
\t    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
\t    at org.testng.TestRunner.privateRun(TestRunner.java:767)
\t    at org.testng.TestRunner.run(TestRunner.java:617)
\t    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
\t    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
\t    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
\t    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
\t    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
\t    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
\t    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
\t    at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
\t    at org.testng.TestNG.run(TestNG.java:1030)
\t    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
\t    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
\t    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
</short-stacktrace>
                    </exception>
                </test-method>
            </class>
        </test>
    </suite>
</testng-results>